####################################################
#   KnockbackMaster by xDefcon <luigi@xdefcon.com>
# www.spigotmc.org/resources/knockbackmaster.42721/
#                Configuration File
####################################################

# Should the plugin notify OPs when a new update is released? (SUGGESTED VALUE IS "true")
update-notify: true

#**************************************************#
#                    KNOCKBACK                     #
#**************************************************#
# Section related to the Knockback multipliers.
# 1.0 means "standard" KB, for instance 1 block.
# 1.1 means 10% more than the previous knockback.
# Please consider that the knockback is processed
# with a certain order.
#**************************************************#
knockback:
  normal:
    # Horizontal knockback, affects only X and Z coordinate values.
    horizontal: 0.4
    # Vertical knockback, affects only Y coordinate value.
    vertical: 0.36

  # Sprinting knockback values. This multipliers will be used if the damager is sprinting
  # By default in Minecraft, if the damager player is sprinting, he deals more knockback to the damaged one.
  # This is the reason of PvP movement-related actions like W-tapping.
  sprinting:
    # Horizontal sprint knockback, affects only X and Z coordinate values.
    horizontal: 0.8
    # Vertical sprint knockback, affects only Y coordinate value.
    vertical: 0.42

  # Air knockback values. Section related to the knockback that a player should receive if in air.
  # Usually, if the damaged player is taking damage while he's in the air, he will receive less knockback
  # both horizontally and vertically.
  air:
    # Air Multiplier, 1.0 means no difference, 0.8 means 20% less knockback while in air.
    in-air-multiplier: 0.8

  # Enchantment section.
  enchantment:
    # If the damager player has Knockback enchantment, the dealt knockback will be multiplied by this value.
    # 1.1 means 10% more knockback for Knockback I, 2.2 for Knockback II etc.
    knockback-multiplier: 1.1

#**************************************************#
#                     W-TAPPING                    #
#**************************************************#
w-tap:
  # Should the w-tap manager be enabled and check when a player is w-tapping?
  enabled: true

  # Set this to true to enable debug mode. Debug mode will send a notification to OPs every tick that notify them
  # when he is w-tapping or not. This is useful to check the w-tap values to see if the delays works for your pvp style.
  debug: false

  # How long (in ticks, 1 tick = 50ms) should the player stand still before detecting him as NOT moving?
  not-moving-delay: 2

  # What is the maximum delay (ms) between pressing W key twice (sprinting/not sprinting) for detecting a player as w-tapping?
  # Lower value = pressing W faster for valid w-tap. Higher value = more easy to w-tap.
  # (Please set values near multiples of 50 like: 150, 160, 195, 200, 455 to be more accurate as possible.)
  sprinting-delay-ms: 200

  # Section related to W-tap knockback modifiers. The knockback will be multiplied by this value.
  # 1.05 means 5% MORE knockback while 0.98 means 2% LESS knockback (suggestion: keep this values between -10% and +10%)
  knockback-modifier:
      # kb modifiers for attacker player, this is the knockback (modifier) you DEAL if w-tapping:
      as-damager:
          horizontal: 1.05
          vertical: 1.03
      # kb modifiers for danaged player, this is the knockback (modifier) you RECEIVE if w-tapping:
      as-damaged:
          horizontal: 0.95
          vertical: 0.97

#**************************************************#
#                   COMBO MODE                     #
#**************************************************#
combo-mode:
  # Should the combo mode be enabled when a player eats an enchanted golden apple?
  enabled: false

  # Set this to true if you want to notify players when combo mode is enabled (after eating gapple)
  # and disabled (when the time is expired). You can edit the messages in the messages.yml config file.
  notify-player: true

  # How long should the combo effect be active? Set this value in seconds.
  gapple-duration: 30

  # No damage ticks (basically set this to 1 if you want allow 20 hits per sec. 2 if 10 etc.)
  # This value represent the number of ticks that should occur between 2 hits.
  no-damage-ticks: 3

#**************************************************#
#                   RANDOMIZER                     #
#**************************************************#
randomizer:
  # Set this to false if you want to DISABLE the randomize feature.
  enabled: true

  # Section related to random knockback modifiers. Values are in percentage.
  modifier:
    # Horizontal maximum percentage factor. (5 means that a maximum of 5% will be randomly added for each hit)
    horizontal: 4
    # Vertical maximum percentage factor.
    vertical: 2
